# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-01-23 08:51:38
"""
import arcpy

def Model(path_to_indicator, path_to_gdb):  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Conversion Tools.tbx")
    path_to_indicator = "C:\\Users\\patwood\OneDrive - Sacramento Area Council of Governments\\Task 8. Reproduce Progress Report indicators\\Indicator Data\\Pop_2V2.csv"
    path_to_gdb = "I:\\Monitoring and Reporting\\PublishTables\\Default.gdb"

    # Process: Table To Geodatabase (Table To Geodatabase) (conversion)
    Default_gdb = arcpy.conversion.TableToGeodatabase(Input_Table=[path_to_indicator], Output_Geodatabase=path_to_gdb)[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="I:\\Monitoring and Reporting\\PublishTables\\Default.gdb", workspace="I:\\Monitoring and Reporting\\PublishTables\\Default.gdb"):
        Model()
